version: "3.9"

services:
    database: 
        image: postgres
        container_name: sistema-de-controle-de-compravante-de-alugueis-back-end
        restart: always
        ports: 
            - 5432:5432
        environment:
             - POSTGRES_USER=docker
             - POSTGRES_PASSWORD=pscode
             - POSTGRES_DB=database
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: sistema-de-controle-de-compravante-de-alugueis-app
        restart: always
        ports:
            - 3334:3334
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database
volumes:
    pgdata:
        driver: local